dist: xenial
sudo: true
language: ruby
cache: bundler
services:
  - rabbitmq
  - redis-server
before_install:
  - gem install bundler
before_script:
  - "./bin/ci/install_on_debian.sh"
  - until sudo lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
rvm:
  - ruby-head
  - "2.6.3"
  - "2.5.5"
  - "2.4.6"
  - "2.3.8"
matrix:
  include:
    - rvm: "2.6.3"
      env: INTEGRATION_LOG=1 INTEGRATION=1
  allow_failures:
    rvm:
      - ruby-head
